### ISSUE TITLE
OpenPlayer is referenced as openplayer

### ISSUE THREAD

**Issue by ghost** [CommonsLab/CommonsLab#2]
On case-sensitive file system compilation fails because the `openplayer` dependency is stored in `OpenPlayer` directory.

**Comment by valdio** [comment]
This issue doesn't seem to happen to me.
Anyway, I fixed what I thought was the probable cause.

**Comment by AleksanderKoko** [comment]
Hi @valdio , @krt16s . Is this issue still relevant? Can we test to be sure its gone?

Thanks @krt16s for pointing this out.
